#!/bin/bash

# --- Configuration ---

# List of region codes for the road networks
REGIONS=(
    "USA" "CTR" "W" "E" "LKS" "CAL" 
    "NE" "NW" "FLA" "COL" "BAY" "NY"
)

# Define the query file types/suffixes generated by 'query_generator'
QUERY_TYPES=("random_pairs")
# Add the 10 distance-bucketed files (dist_bucket_0 to dist_bucket_9)
for i in {0..9}; do
    QUERY_TYPES+=("dist_bucket_${i}")
done

# Binary names and directories
QUERY_BIN="./query"
INDEX_SUFFIX=".idx_dcl"
# Must match the OUTPUT_DIR in generate_queries.sh
QUERY_DIR="queries" 

echo "Starting Query Execution for ${#REGIONS[@]} datasets across ${#QUERY_TYPES[@]} query sets each."
echo "Total expected runs: $((${#REGIONS[@]} * ${#QUERY_TYPES[@]}))"
echo "------------------------------------------------------------------------------------------------"

# Check if query executable exists
if ! [ -x "$QUERY_BIN" ]; then
    echo "Error: '$QUERY_BIN' executable not found or not executable."
    echo "Please ensure you have compiled your project successfully (e.g., 'make query')."
    exit 1
fi

TOTAL_RUNS=0
SUCCESS_RUNS=0

# Loop 1: Iterate over regions (datasets)
for region in "${REGIONS[@]}"; do
    # Index files are expected to be in the current directory, e.g., USA-road-d.USA.idx
    INDEX_FILE="USA-road-d.${region}${INDEX_SUFFIX}"
    
    if [ ! -f "$INDEX_FILE" ]; then
        echo "Skipping region ${region}: Index file ${INDEX_FILE} not found. Ensure indexing completed."
        continue
    fi

    # Loop 2: Iterate over query set types (random or bucketed)
    for type_suffix in "${QUERY_TYPES[@]}"; do
        # Construct the full query filename based on the generator script's output
        # e.g., queries/USA_random_pairs.txt or queries/USA_dist_bucket_5.txt
        QUERY_FILENAME="${region}_${type_suffix}.txt"
        QUERY_FILE="${QUERY_DIR}/${QUERY_FILENAME}"
        
        TOTAL_RUNS=$((TOTAL_RUNS + 1))

        if [ -f "$QUERY_FILE" ]; then
            
            # Print combination for easy grepping
            # Format: RUN: REGION | QUERY_TYPE
            echo "--- RUN: ${region} | ${type_suffix} ---"
            
            # Execute the query binary: ./query <index_file> <query_file>
            $QUERY_BIN "$INDEX_FILE" "$QUERY_FILE"
            
            if [ $? -eq 0 ]; then
                SUCCESS_RUNS=$((SUCCESS_RUNS + 1))
            else
                echo "Error: Execution failed for ${region} with ${type_suffix}. Check './query' output."
            fi

        else
            echo "Skipping query set ${type_suffix} for ${region}: Query file ${QUERY_FILE} not found. Ensure query generation completed."
        fi
    done
    echo "------------------------------------------------------------------------------------------------"
done

echo "Benchmark completed."
echo "Summary: ${SUCCESS_RUNS} successful runs out of ${TOTAL_RUNS} total runs."
